### ISSUE TITLE
External Event Handlers - Rotate with buttons?

### ISSUE THREAD

**Issue by clandestine8** [VoidCanvas/3dEye#2]
Trying to decipher your code to make this rotate with button events calls. I havent got it working yet - was hoping for some insight?

**Comment by ThomasBush** [comment]
I would like a similar interaction, is this currently possible?  I would need access to next and previous event handlers. @clandestine8 did you figure this out?

**Comment by metalshan** [comment]
I think you can do that very easily. If you see the code (in develop branch) you just have to put the code in touchmove in a function and call it (the parameters need to be adjusted).

Reply back if you want a similar code. I think I did this for someone long ago.
